[package]
name = "clickhouse-db"
edition = "2024"
version = "0.0.1"

[dependencies]
clickhouse = "0.12.2"
env_logger = "0.11.8"
log = "0.4.27"

[lib]
path = "src/lib.rs"
name = "clickhouse_db"
plugin = false
proc-macro = false
edition = "2024"
required-features = []
crate-type = ["lib"]
