[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.28"
postgres = { version = "0.1.0", path = "../postgres-db" }
redis = { version = "0.1.0", path = "../redis-db" }
tokio = "1.47.1"
validator = "0.20.0"
