[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0.219", features = ["derive"]}
jsonwebtoken = "8" # Or the latest version
actix-web = "4.11.0"
serde_json = "1.0.142"
dotenv = "0.15.0"
httpstatus = "0.1.2"
log = "0.4.27"
