name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: [5432:5432]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cex
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports: [6379:6379]
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      clickhouse:
        image: clickhouse/clickhouse-server:24
        ports: [8123:8123, 9000:9000]
        env:
          CLICKHOUSE_USER: default
          CLICKHOUSE_PASSWORD: ""
        options: >-
          --health-cmd "clickhouse-client --query 'SELECT 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/cex
      REDIS_URL: redis://localhost:6379
      CLICKHOUSE_HOST: localhost
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_CONNECT_TIMEOUT_SECONDS: 5
      CLICKHOUSE_MAX_CONNECTIONS: 10
      CLICKHOUSE_QUERY_TIMEOUT_SECONDS: 60

    steps:
      - uses: actions/checkout@v4

      # Cache dependencies
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      # Install Rust
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Build and test each service separately
      - name: Build API
        working-directory: ./api
        run: cargo build --verbose

      - name: Build WebSocket
        working-directory: ./ws
        run: cargo build --verbose

      - name: Build Engine
        working-directory: ./engine
        run: cargo build --verbose

      - name: Build Redis-DB
        working-directory: ./redis-db
        run: cargo build --verbose
      
      - name: Build Postgres-DB
        working-directory: ./postgres-db
        run: cargo build --verbose
      
      - name: Build Clickhouse-DB
        working-directory: ./clickhouse-db
        run: cargo build --verbose
